# Generated by Django 2.2.dev20181002231723 on 2019-09-11 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagetwo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ebregister',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('mail', models.EmailField(max_length=30)),
            ],
            options={
                'db_table': 'ebregister',
            },
        ),
    ]
